# Generated by Django 4.1 on 2022-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_used_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_storage',
            field=models.CharField(default=60000, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='used_storage',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
